%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% sphlap.m - Compute the smoother and Laplacian matrices using spherical
%            splines.
% Usage: [S, L] = sphlap (K, LapK, T, Q1, Q2, R, lambda);
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Required Inputs
% K, LapK, T, Q1, Q2, R    matrices generated by sphlapo 
%                lambda    smoothing parameter
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Output:
%                     S    the smoother matrix
%                     L    the Laplacian matriz

%% CREDIT
% Claudio Carvalhaes, J. Acacio de Barros,
% The surface Laplacian technique in EEG: Theory and methods,
% International Journal of Psychophysiology,
% Volume 97, Issue 3,
% 2015,
% Pages 174-188,
% ISSN 0167-8760,
% https://doi.org/10.1016/j.ijpsycho.2015.04.023.

%% CHANGES
% 2024-Aug  The output includes the coefficients, for later interpolation
%           Modification by Enciso-Alva.

function [S, L] = sphlap_interp (K, LapK, C, D)

S = K*C + D; % The smoother matrix 
L = LapK*C;    % The Laplacian matrix

end