%% CREDIT
% Claudio Carvalhaes, J. Acacio de Barros,
% The surface Laplacian technique in EEG: Theory and methods,
% International Journal of Psychophysiology,
% Volume 97, Issue 3,
% 2015,
% Pages 174-188,
% ISSN 0167-8760,
% https://doi.org/10.1016/j.ijpsycho.2015.04.023.﻿

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% sphlap.m - Compute the smoother and Laplacian matrices using spherical
%            splines.
% Usage: [S, L] = sphlap (K, LapK, T, Q1, Q2, R, lambda);
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Required Inputs
% K, LapK, T, Q1, Q2, R    matrices generated by sphlapo 
%                lambda    smoothing parameter
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Output:
%                     S    the smoother matrix
%                     L    the Laplacian matriz

function [S, L] = sphlap (K, LapK, T, Q1, Q2, R, lambda)

% Handle arguments
if nargin ~= 7
  help sphlap.m;
  return;
end

I = eye( size(K, 1) );
Klamb = K + lambda*I;

C = Q2 / (Q2' * Klamb * Q2) * Q2'; 
D = R \ Q1' * (I - Klamb*C);

S = K*C + T*D; % The smoother matrix 
L = LapK*C;    % The Laplacian matrix

end